package com.timi.seulseul.presentation.common.constants

const val BASE_ROUTE_ID = "baseRouteId"
const val IS_FIRST_RUN = "isFirstRun"
const val KEY_DENIED_COUNT = "deniedCount"
const val KEY_NOTI_DENIED_COUNT = "notiDeniedCount"
const val FCM_TOKEN = "fcm_token"
const val EXTRA_ROAD_ADDR = "roadAddr"
const val EXTRA_JIBUN_ADDR = "jibunAddr"
const val END_NICKNAME = "endNickName"
const val ALARM_TIME = "alarmTime"
const val ALARM_TERM = "alarmTerm"
const val ALARM_ID = "alarmId"
const val ALARM_ON = "alarmOn"
const val TODAY = "today"
const val REFRESH = "refresh"
const val TODAY_ALARM = "todayAlarm"
const val IS_NOT_FIRST = "isNotFirst"
const val POINT_ALARM_OFF = "pointAlarmOff"
const val KEY_ONBOARDING = "KEY_ONBOARDING"
const val KEY_UUID = "KEY_UUID"
const val AUTH = "Auth"